### ISSUE TITLE
Build step failed: basedir didn't exist

### ISSUE THREAD

**Issue by vikrama** [nassendelft/jenkins-plugin-google-driver-uploader#1]
Is this something from the plugin itself? I verified and this directory does exist in the slave

```
ERROR: Build step failed with exception
java.lang.IllegalStateException: basedir /Users/jenkins/slave/workspace/android-build-apk-playstore-alpha does not exist.
	at org.apache.tools.ant.DirectoryScanner.scan(DirectoryScanner.java:879)
	at com.anicks.googledriveupload.GoogleDriveUploader.listFiles(GoogleDriveUploader.java:66)
	at com.anicks.googledriveupload.GoogleDriveUploader.perform(GoogleDriveUploader.java:50)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

**Comment by nassendelft** [comment]
Sorry about that, i probably should've deleted this project. This project never completed and i don't think i'll ever will.
